package test;

import static org.junit.jupiter.api.Assertions.*;

import java.util.Arrays;
import java.util.List;

import org.junit.jupiter.api.Test;

import main.NumberSequenceGenerator;

/**
 * The is TDD test class that validates the number generator class.
 */
public class NumberSequenceGeneratorTest {

	NumberSequenceGenerator numberSeqGen = new NumberSequenceGenerator();

	/**
	 * This Test runs the positive case by validating the expected value is present
	 * in the output generated by the program.
	 */
	@Test
	void ascendingDigitsPositiveTest() {

		String out = numberSeqGen.generateNumberSequence(2);
		List<String> outlist = Arrays.asList(out.split(","));
		String expectedOutput = "22";
		assertTrue(outlist.contains(expectedOutput));

	}

	/**
	 * This Test runs the negative test case by validating the expected value is not
	 * present in the output generated by the program.
	 */
	@Test
	void ascendingDigitsNegativeTest() {

		String out = numberSeqGen.generateNumberSequence(3);
		List<String> outlist = Arrays.asList(out.split(","));
		String expectedOutput = "554";
		assertFalse(outlist.contains(expectedOutput));

	}

	/**
	 * This Test runs the test case for the input value of zero.
	 */
	@Test
	void ascendingDigitsZeroTest() {

		String out = numberSeqGen.generateNumberSequence(0);
		assertEquals("", out);
	}

}
